// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Units.Core
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class GenerateUnits : GenerateUnitsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\nnamespace Numbers {\n    public interface IReal<T> where T: IReal<T> {\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
 foreach(var meth in SelfOps) { 
            
            #line default
            #line hidden
            this.Write("\n             public ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.RetType ?? "T"));
            
            #line default
            #line hidden
            this.Write(" Op");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Name));
            
            #line default
            #line hidden
            this.Write("(T op2);\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n    }\n}\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  foreach(var r in RealDefs) { 
            
            #line default
            #line hidden
            this.Write("\nnamespace Numbers.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("s {\n    using Numbers;\n    using System;\n    using Scalar = Numbers.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("s.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(";\n\n    public readonly struct ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" : IEquatable<");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(">, IReal<");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("> {\n        private readonly ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.ClrName));
            
            #line default
            #line hidden
            this.Write(" _data;\n        public ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.ClrName));
            
            #line default
            #line hidden
            this.Write(" data) {\n            _data = data;\n        }\n        public ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" data) {\n            _data = data._data;\n        }\n        public static implicit" +
                    " operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.ClrName));
            
            #line default
            #line hidden
            this.Write(" raw) => new ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("(raw);\n        public static explicit operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.ClrName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" raw) => raw._data;\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
 foreach(var meth in SelfOps) { 
            
            #line default
            #line hidden
            this.Write("\n            public ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.RetType ?? r.WrapName));
            
            #line default
            #line hidden
            this.Write(" Op");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" op2) {\n                return _data ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Symbol));
            
            #line default
            #line hidden
            this.Write(" op2._data;\n            }\n            public static ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.RetType ?? r.WrapName));
            
            #line default
            #line hidden
            this.Write(" operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Symbol));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" op1, ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" op2) {\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  if (meth.RetType != null) { 
            
            #line default
            #line hidden
            this.Write("\n                return op1._data ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Symbol));
            
            #line default
            #line hidden
            this.Write(" op2._data;\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("\n                return new ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write("(op1._data ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Symbol));
            
            #line default
            #line hidden
            this.Write(" op2._data);\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n            }\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EdgeOps(Scalar)));
            
            #line default
            #line hidden
            this.Write("\n        public override bool Equals(object obj) => obj is ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" wn && Equals(wn);\n        public bool Equals(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(r.WrapName));
            
            #line default
            #line hidden
            this.Write(" other) => this._data == other._data;\n        public override int GetHashCode() =" +
                    "> _data.GetHashCode();\n        public override string ToString() => _data.ToStri" +
                    "ng();\n    }\n}\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  foreach(var real in RealDefs) { 
            
            #line default
            #line hidden
            this.Write("\nnamespace Units.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.WrapName));
            
            #line default
            #line hidden
            this.Write(" {\n    using Numbers.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.WrapName));
            
            #line default
            #line hidden
            this.Write("s;\n    using System;\n    using Scalar = Numbers.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.WrapName));
            
            #line default
            #line hidden
            this.Write("s.");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.WrapName));
            
            #line default
            #line hidden
            this.Write(";\n\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  foreach(var unit in Units.Where(i => i.Name != "Scalar")) { 
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  Console.WriteLine(unit); 
            
            #line default
            #line hidden
            this.Write("\n    public readonly struct ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(": IEquatable<");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("> {\n        public readonly Scalar RawValue;\n        public ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(Scalar value) {\n            RawValue = value;\n        }\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
 foreach(var meth in SelfOps.Where(i => i.Symbol != "*" && i.Symbol != "/")) { 
            
            #line default
            #line hidden
            this.Write("\n            public static ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.RetType ?? unit.Name));
            
            #line default
            #line hidden
            this.Write(" operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Symbol));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" op1, ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" op2) =>\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  if (meth.RetType == null) { 
            
            #line default
            #line hidden
            this.Write("\n                new ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(op1.RawValue.Op");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Name));
            
            #line default
            #line hidden
            this.Write("(op2.RawValue));\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(op1.RawValue.Op");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Name));
            
            #line default
            #line hidden
            this.Write("(op2.RawValue));;\n                ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n        ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EdgeOps(unit)));
            
            #line default
            #line hidden
            this.Write("\n\n        public static explicit operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.ClrName));
            
            #line default
            #line hidden
            this.Write(" from) => new ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(from);\n        public static explicit operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(Scalar from) => new ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write("(from);\n        public static explicit operator Scalar(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" from) => from.RawValue;\n        public static explicit operator ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.ClrName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" from) => (");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(real.ClrName));
            
            #line default
            #line hidden
            this.Write(")from.RawValue;\n        public override bool Equals(object obj) => obj is ");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" ut && this.Equals(ut);\n        public bool Equals(");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(unit.Name));
            
            #line default
            #line hidden
            this.Write(" other) => true; //return other != null && this == other;\n        public override" +
                    " int GetHashCode() => RawValue.GetHashCode();\n    }\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\n}\n");
            
            #line 1 "C:\Users\Branimir\Source\repos\OriginalLibs\CoreUnits\Units.Core\GenerateUnits.tt"
  } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class GenerateUnitsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
