name: Publish Documentation

on:
  repository_dispatch:
    types: [gen-docs]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: clone
      uses: actions/checkout@v2
      with: 
        repository:  branc116/units-core-docfx
        submodules: 1
    - name: Disable telemetry
      run: ([System.Environment]::SetEnvironmentVariable("DOTNET_CLI_TELEMETRY_OPTOUT", "1", [System.EnvironmentVariableTarget]::User))
      shell: powershell
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build docs
      run: powershell .\Scripts\PublishDocumentation.ps1
